// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OandaTrader.Infrastructure.Data;

#nullable disable

namespace OandaTrader.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OandaTrader.Domain.Models.Candle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<string>("Granularity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Instrument", "Granularity", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("OandaTrader.Domain.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EngineEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Granularity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentPositions")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDailyLossPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTradesPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MlConfidenceThreshold")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PausedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PausedReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetrainAfterTradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RiskPercentPerTrade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineEnabled = false,
                            Granularity = "M15",
                            MaxConcurrentPositions = 3,
                            MaxDailyLossPercent = 3.0m,
                            MaxTradesPerDay = 10,
                            MlConfidenceThreshold = 0.55m,
                            RetrainAfterTradeCount = 25,
                            RiskPercentPerTrade = 1.0m
                        });
                });

            modelBuilder.Entity("OandaTrader.Infrastructure.Data.Entities.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Granularity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("OandaTrader.Infrastructure.Data.Entities.CircuitBreakerEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredLimit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CircuitBreakerEvents");
                });

            modelBuilder.Entity("OandaTrader.Infrastructure.Data.Entities.InstrumentSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Instrument")
                        .IsUnique();

                    b.ToTable("InstrumentSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = true,
                            Instrument = "EUR_USD"
                        },
                        new
                        {
                            Id = 2,
                            Enabled = true,
                            Instrument = "GBP_USD"
                        },
                        new
                        {
                            Id = 3,
                            Enabled = true,
                            Instrument = "USD_JPY"
                        },
                        new
                        {
                            Id = 4,
                            Enabled = true,
                            Instrument = "AUD_USD"
                        });
                });

            modelBuilder.Entity("OandaTrader.Infrastructure.Data.Entities.ModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TrainedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingSampleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("OandaTrader.Infrastructure.Data.Entities.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MlConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("OandaTradeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PnL")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategySource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Units")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Instrument");

                    b.HasIndex("Outcome");

                    b.HasIndex("StrategySource");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
